# Generated by Django 3.1.4 on 2021-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15, null=True)),
                ('Apellido', models.CharField(max_length=10, null=True)),
                ('Email', models.CharField(max_length=50, null=True, unique=True)),
                ('Cedula', models.IntegerField(max_length=30, null=True)),
                ('Img', models.ImageField(upload_to='')),
                ('Pais', models.CharField(max_length=50)),
                ('Entidad_de_salud', models.CharField(max_length=80)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
